const preguntas = [
    new Pregunta(1,"Geografía","¿Cuál es el idioma más hablado en Suiza?","Alemán","Inglés","Italiano","Francés"),
    new Pregunta(2,"Geografía","¿Qué país está entre Perú y Colombia?","Ecuador","México","Venezuela","Bolivia"),
    new Pregunta(3,"Geografía","¿Cuál es el río más largo de Europa Occidental?","Rin","Volga","Danuvio","Ural"),
    new Pregunta(4,"Geografía","¿Qué lago baña la ciudad de Ginebra?","Leman","Ness","Tititcaca","Victoria"),
    new Pregunta(5,"Geografía","¿En qué país europeo se habla el magyar?","Hungría","Ucrania","Austria","Malta"),
    new Pregunta(6,"Geografía","¿Qué palabra significa “hijo de” en los apellidos escoceses?","Mac","Grant","Son","Fil"),
    new Pregunta(7,"Geografía","¿Cuál es la capital de Indonesia?","Jakarta","Surabaya","Medán","Bandung"),
    new Pregunta(8,"Geografía","¿En qué país se encuentra el pico Aconcagua?","Argentina","Chile","Uruguay","Paraguay"),
    new Pregunta(9,"Geografía","¿En qué hemisferio se encuentra Jamaica?","Norte","Sur","Este","Oeste"),
    new Pregunta(10,"Geografía","¿A qué país pertenece la isla de Creta?","Grecia","Noruega","Suecia","Finlandia"),
    new Pregunta(11,"Entretenimiento","¿Cuál es el oso más famoso del parque nacional de Yellowstone?","El oso Yogui","El oso amoroso","El oso Teddy","El oso Misha"),
    new Pregunta(12,"Entretenimiento","¿Qué actor, que no era el feo ni el malo, era el bueno?","Clint Eastwood","John Wayne","Gary Cooper","Henry Fonda"),
    new Pregunta(13,"Entretenimiento","¿Con qué director de cine italiano se casó la actriz Giulietta Masina?","Federico Fellini","Roman Polanski","Michael Haneke","Francis Ford Coppola"),
    new Pregunta(14,"Entretenimiento","¿Quién fue la gran ganadora de los Grammy Latinos 2018?","Rosalía","Shakira","Rozalén","Lady Gaga"),
    new Pregunta(15,"Entretenimiento","¿Cuál de los Siete Enanitos no tenía barba?","Mudito","Gruñón","Sabio","Dormilón"),
    new Pregunta(16,"Entretenimiento","¿Qué conocido actor español protagonizó “La máscara del Zorro” en 1998?","Antonio Banderas","Javier Bardem","Hugo Silva","Quim Gutiérrez"),
    new Pregunta(17,"Entretenimiento","¿Cuál es el tipo de música por el que se conoció mundialmente Astrud Gilberto?","Bossa Nova","Blues","Reggaetton","Dance"),
    new Pregunta(18,"Entretenimiento","¿Qué canción de Los Beatles ha sido la más grabada?","Yesterday","Let it be","Yellow submarine","Hey Jude"),
    new Pregunta(19,"Entretenimiento","¿Quién dijo: “Hitler me ha copiado el bigote”?","Charlie Chaplin","Salvador Dalí","Albert Einstein","Freddy Mercuri"),
    new Pregunta(20,"Entretenimiento","¿Quién fue la primera voz de Mickey Mouse?","Walt Disney","Jim Cummings","Mark Hamill","Seth MacFarlane"),
    new Pregunta(21,"Historia","¿Qué reina británica era hija de los Reyes Católicos?","Catalina de Aragón","Isabel I de Castilla","Victoria del Reino Unido","Isabel I de Inglaterra"),
    new Pregunta(22,"Historia","¿Qué país fue llamado la Galia por los romanos?","Francia","Italia","Portugal","España"),
    new Pregunta(23,"Historia","¿Qué batalla crucial tuvo lugar en 1815?","Waterloo","La batalla del Somme","La batalla de Stalingrado","La batalla de Berlín"),
    new Pregunta(24,"Historia","¿Cuál era la ciudad hogar de Marco Polo?","Venecia","París","Roma","Lisboa"),
    new Pregunta(25,"Historia","¿Quién era el emperador de Roma cuando murió Jesús?","Tiberio","Glicerio","Julio Nepote","Rómulo Augústulo"),
    new Pregunta(26,"Historia","¿Cómo se conoce a la policía italiana?","Carabinieri","Polizia","Gendarmería","Heimevernet"),
    new Pregunta(27,"Historia","¿Cuál fue la dictadura que comenzó en España en el año 1923?","La del general Primo de Rivera","La de Fidel Castro","La de Francisco Franco","La de Mussolini"),
    new Pregunta(28,"Historia","¿Quién fue el primer presidente de los Estados Unidos?","George Washington","Donald Trump","John Adam","Thomas Jefferson"),
    new Pregunta(29,"Historia","¿Qué país africano fue fundado en 1847 por esclavos americanos liberados?","Liberia","Nigeria","Kenia","Malí"),
    new Pregunta(30,"Historia","¿En qué ciudad se entrevistaron Franco y Hitler?","Hendaya","París","Madrid","Berlín"),
    new Pregunta(31,"Arte y Literatura","¿Qué escribía un testador?","Testamentos","Escrituras","Novelas","Opiniones"),
    new Pregunta(32,"Arte y Literatura","¿Quién visitó un país gobernado por caballos?","Gulliver","Sherlock Holmes","Oliver Twist","Hércules Poirot"),
    new Pregunta(33,"Arte y Literatura","¿Cuál era el lema de los Tres Mosqueteros?","Todos para uno y uno para todos","Cuando el grajo vuela bajo, hace un frío del carajo","Haz el amor y no la guerra","Cada día sabemos más y entendemos menos"),
    new Pregunta(34,"Arte y Literatura","¿Qué tiene en Segovia 128 arcos?","El Acueducto","El club de tiro con arco","La iglesia gótica de Pedraza","El puente del diablo"),
    new Pregunta(35,"Arte y Literatura","¿Quién fue el italiano que puso música al Othelo de Shakespeare?","Verdi","Raffaella Carrà","Vivaldi","Rossini"),
    new Pregunta(36,"Arte y Literatura","¿Quién escribió La Guerra de los Mundos en 1898?","H.G. Wells","William Faulkner","Oscar Wilde","Franz Kafka"),
    new Pregunta(37,"Arte y Literatura","¿De qué asignatura fue catedrático Antonio Machado?","Francés","Filosofía","Historia","Biología"),
    new Pregunta(38,"Arte y Literatura","¿Quién escribió las aventuras de Sandokán?","Emilio Salgari","William Shakespeare","Philip K. Dick","Gabriel García Márquez"),
    new Pregunta(39,"Arte y Literatura","¿Cuál es la identidad secreta de Don Diego de la Vega?","El Zorro","Lady Bug","Batman","El llanero solitario"),
    new Pregunta(40,"Arte y Literatura","¿Qué mide en París alrededor de 333 metros?","La Torre Eiffel","La pirámide del Lovre","El arco del Triunfo","La catedral de Notre Dame"),
    new Pregunta(41,"Ciencias y Naturaleza","¿Cómo se llaman las células nerviosas?","Neuronas","Fibroblastos","Adipocitos","Epiteliales"),
    new Pregunta(42,"Ciencias y Naturaleza","¿Qué es más valioso?","Brillante","Diamante","Oro","Cobre"),
    new Pregunta(43,"Ciencias y Naturaleza","¿Cuál es el pájaro símbolo de la paz?","Paloma","Periquito","Verderón","Canario"),
    new Pregunta(44,"Ciencias y Naturaleza","¿En qué mes el sol está más cerca de la Tierra?","Diciembre","Febrero","Agosto","Octubre"),
    new Pregunta(45,"Ciencias y Naturaleza","¿En qué parte del cuerpo se encuentra la piel más gruesa?","Espalda","Muslo","Oreja","Planta del pie"),
    new Pregunta(46,"Ciencias y Naturaleza","¿A qué le tiene miedo una persona que sufre vértigo?","A las alturas","A la velocidad","Al exterior","A los espacios cerrados"),
    new Pregunta(47,"Ciencias y Naturaleza","¿Cómo se llama la ciencia que estudia la sangre?","Hematología","Cardiología","Fisiología","Geología"),
    new Pregunta(48,"Ciencias y Naturaleza","¿Qué fabricó Alessandro Volta, por primera vez, en 1800?","Pila","Bombilla","Teléfono","Rueda"),
    new Pregunta(49,"Ciencias y Naturaleza","¿Cuál de los cinco sentidos se desarrolla el primero?","Olfato","Vista","Tacto","Gusto"),
    new Pregunta(50,"Ciencias y Naturaleza","¿Cuál es el dedo más sensible de la mano?","Índice","Pulgar","Corazón","Meñique"),
    new Pregunta(51,"Deportes y Pasatiempos","¿Qué pieza de ajedrez puede hacer un movimiento en forma de L?","Caballo","Peón","Reina","Rey"),
    new Pregunta(52,"Deportes y Pasatiempos","¿Cómo se llaman los deportistas que practican el judo?","Judokas","Karatecas","Futbolistas","Judíos"),
    new Pregunta(53,"Deportes y Pasatiempos","¿Qué deporte practican los Harlem Globetrotters?","Baloncesto","Fútbol","Atletismo","Tenis"),
    new Pregunta(54,"Deportes y Pasatiempos","¿A cuántos puntos se disputa un set en el tenis de mesa?","Veintiuno","Diez","Veinticuatro","Cuarenta"),
    new Pregunta(55,"Deportes y Pasatiempos","¿Qué obtienes si añades fruta fresca al vino tinto?","Sangría","Calimocho","Gintonic","Salmorejo"),
    new Pregunta(56,"Deportes y Pasatiempos","¿A qué equipo de fútbol pertenecía el estadio Metropolitano?","Atlético de Madrid","Real Madrid","Betis","Barcelona"),
    new Pregunta(57,"Deportes y Pasatiempos","¿En qué país se encuentra el circuito de Le Mans?","Francia","Italia","Alemania","Portugal"),
    new Pregunta(58,"Deportes y Pasatiempos","¿Quién fueron los finalistas de baloncesto en los Juegos Olímpicos de Los Ángeles de 1984?","España y Estados Unidos","España y Alemania","Italia y Francia","Francia y Suecia"),
    new Pregunta(59,"Deportes y Pasatiempos","¿Cuál era el nombre anterior de Muhammad Alí?","Cassius Clay","Carlos Monzón","Floyd Mayweather, Jr.","Pernell Whitaker"),
    new Pregunta(60,"Deportes y Pasatiempos","¿Cuántos jugadores tiene un equipo de voleibol?","Seis","Ocho","Cuatro","Once"),
    new Pregunta(61,"Cultura popular","¿Quién fue el primer presentador del concurso 'Un, dos, tres, responda otra vez' que se emitía en Televisión Española?","Kiko Ledgard","Mayra Gómez Kemp","Jordi Estadella","Luis Larrodera"),
    new Pregunta(62,"Cultura popular","¿En qué popular serie de TV podemos ubicar a un personaje llamado Walter White?","En Breaking Bad","Juego de Tronos","Big Bang Theory","Friends"),
    new Pregunta(63,"Cultura popular","¿Qué popular serie de Netflix nos habla sobre la vida del narcotraficante Pablo Escobar Gaviria?","Narcos","Breaking Bad","Fariña","Ozark"),
    new Pregunta(64,"Cultura popular","¿Qué actor interpreta el personaje de Leonard Hofstadter en la serie 'The Big Bang Theory'?","Johnny Galecki","Jim Parsons","Kunal Nayyar","Simon Helberg"),
    new Pregunta(65,"Cultura popular","¿Cuál es el nombre de pila del aventurero Bear Grylls?","Edward","Peter","Jim","Philip"),
    new Pregunta(66,"Cultura popular","¿Cómo se llama el actor que interpreta al Dr House?","Hugh Laurie","Johny Depp","Keanu Reeves","Samuel L. Jackson"),
    new Pregunta(67,"Cultura popular","¿Cuáles son los apellidos de los cirujanos que protagonizan la serie 'Nip/Tuck'?","McNamara y Troy","Johnson y Smith","Brown y Miller","Jones y Davis"),
    new Pregunta(68,"Cultura popular","¿Qué artista tiene en su poder más premios Grammy?","Georg Solti","Madonna","Michael Jackson","Julio Iglesias"),
    new Pregunta(69,"Cultura popular","¿Qué artista tiene en su poder más premios Emmy?","Julia Louis Dreyfus","Lee Jung-jae","Zendaya ","Jason Sudeikis"),
    new Pregunta(70,"Cultura popular","¿Qué jugador de la NBA fue pareja durante un tiempo de la popular Kim Kardashian?","Kris Humphries","LeBron James","Anthony Davis","Magic Johnson")
]